name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - "gh-deploy"

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and build
        run: cd web-app && npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
